name: Deploy Frontend
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t shikhax/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true shikhax/react-test npm test
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ReactApp
          environment_name: ReactApp-env
          existing_bucket_name: elasticbeanstalk-us-east-1-891377339446
          use_existing_version_if_available: true
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip